# zuul 网关
server:
  port: 20010
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**  #路由到商品的微服务    key 注册到eureka的服务， value: 路径
    search-service: /search/** #路由到搜索微服务