server:
  port: 20000
spring:
  application:
    name: cloud-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    register-with-eureka: false  #不注册给自己
    fetch-registry: false   #不拉取服务
  server:
    enable-self-preservation: false   #自我保护